spring:
  # 1. Conexão com o Banco de Dados (Postgres)
  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # 2. Configuração do JPA (Hibernate)
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true # Para vermos as queries que o Spring faz por baixo dos panos
    properties:
      hibernate:
        format_sql: true

  # 3. Conexão com o Cache (Redis)
  data:
    redis:
      host: localhost
      port: 6379

  # 4. Controle de Versão do Banco (Flyway)
  flyway:
    enabled: true
    baseline-on-migrate: true

# 5. Perfumaria: Logs coloridos e bem formatados
logging:
  level:
    root: INFO
    dev.rdaltio.cartola_ai: DEBUG # Mostra logs detalhados apenas do NOSSO código